//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model1st
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int ID_SV { get; set; }
        public int ID_Khoa { get; set; }
        public string TenSV { get; set; }
        public double Diem { get; set; }
        public bool GioiTinh { get; set; }
        public System.DateTime NgaySinh { get; set; }
    
        public virtual Khoa Khoa { get; set; }
    }
}
