//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public int ID_SV { get; set; }
        public Nullable<int> ID_Khoa { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<double> Diem { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string TenSV { get; set; }
    
        public virtual KHOA KHOA { get; set; }
    }
}
