//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinhVienEntitiesDB1st : DbContext
    {
        public SinhVienEntitiesDB1st()
            : base("name=SinhVienEntitiesDB1st")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
    }
}
