//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQEntity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int MSSV { get; set; }
        public string Sname { get; set; }
        public Nullable<System.DateTime> Sbirth { get; set; }
        public int FID { get; set; }
        public Nullable<double> DTB { get; set; }
        public Nullable<bool> Gender { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
